In [4]:
import numpy as np

In [5]:
b=np.array([[[1,2],[3,4],[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [7]:
b.shape

(1, 4, 2)

In [5]:
b.ndim

3

In [8]:
b.dtype

dtype('int32')

In [9]:
b.itemsize

4

In [11]:
b.nbytes

32

In [19]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [20]:
a.shape

(2, 7)

In [21]:
a.size

14

In [22]:
a[1,5]

13

In [23]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
a[0,0:-1]

array([1, 2, 3, 4, 5, 6])

In [32]:
a[1,2]=100

In [43]:
a[0,:]=5
a

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [38]:
a[:,2]=5
a

array([[1, 2, 5, 4, 5, 6, 7],
       [5, 5, 5, 5, 5, 5, 5]])

In [44]:
a

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [6]:
c=np.array([3,5,4])

In [14]:
e=np.zeros([5,3])
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
o=np.ones([4,6])
o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [28]:
h=np.full([2,3],6)
f=h.copy()
f
h

array([[6, 6, 6],
       [6, 6, 6]])

In [32]:
h[1,2]=99
h

array([[ 6,  6,  6],
       [ 6,  6, 99]])

In [33]:
f

array([[6, 6, 6],
       [6, 6, 6]])

In [34]:
h

array([[ 6,  6,  6],
       [ 6,  6, 99]])

In [37]:
g=np.full_like(h,h)
g

array([[ 6,  6,  6],
       [ 6,  6, 99]])

In [54]:
g=np.random.rand(4)
print(g)
g
g.shape


[0.44913817 0.91303695 0.35109275 0.31402475]


(4,)

In [53]:
i=np.identity(3)

In [77]:
1233+155+150

1538

In [88]:
arr=np.array([[1,2,3,4]])
r2=np.repeat(arr,3,axis=0)
r2
print(arr)
arr.ndim

[[1 2 3 4]]


2